language: python
python:
  - "3.5"
before_install:
  - sudo add-apt-repository universe
  - sudo apt-get update
  - sudo apt-get install -y direnv
install:
  - pip install poetry
  - poetry install
script:
  - pytest
